DROP TABLE IF EXISTS scan_notifications CASCADE;
DROP TABLE IF EXISTS scan_logs CASCADE;
DROP TABLE IF EXISTS emergency_contacts CASCADE;
DROP TABLE IF EXISTS emergency_profiles CASCADE;
DROP TABLE IF EXISTS activation_codes CASCADE;
DROP TABLE IF EXISTS wristbands CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
